name: Xcode

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pod install
        run: |
          sudo gem install cocoapods
          pod install
      - name: xcodebuild pod
        run: |
          cd Pods
          pod install
          cd ..
      - name: xcodebuild unshaky
        run: |
          xcodebuild CODE_SIGNING_ALLOWED=NO -arch x86_64
