name: Xcode

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: xcodebuild unshaky
        run: |
          xcodebuild CODE_SIGNING_ALLOWED=NO -workspace Unshaky.xcworkspace -scheme Unshaky DONT_CODE_SIGN=YES -configuration Release
